baseURL = 'https://SalmaGhareeb.github.io/me'
languageCode = 'en-us'
title = 'Salma Ghareeb'
theme = 'lynx'

[author]
   name = "Salma Ghareeb"

  links = [
     { email = "mailto:salmahghareeb@gmail.com" },
     { github = "https://github.com/SalmaGhareeb" },
     { linkedin = "https://www.linkedin.com/in/salmahabdelhady/" },
  ]
