baseURL = 'https://SALMAGHAREEB.ME/'
languageCode = 'en-us'
title = 'Salma Ghareeb'
theme = 'lynx'

disableKinds = ["taxonomy", "term"]

[author]
 name = "Salma Ghareeb"
 image = "author.jpg"

links = [
     { email = "mailto:salmahghareeb@gmail.com" },
     { github = "https://github.com/SalmaGhareeb" },
     { linkedin = "https://www.linkedin.com/in/salmahabdelhady/" }
]



[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true