baseURL = 'https://salmaghareeb.me/'
languageCode = 'en-us'
title = 'Salma Ghareeb'
theme = 'anubis2'

[pagination]
pagerSize = 5

[params.author]
name = "Salma Ghareeb"
email = "salmaghareeb@gmail.com"
location = "Berlin"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

# [[menu.main]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = 2

# [[menu.main]]
# identifier = "tags"
# name = "Tags"
# url = "/tags/"
# weight = 3

# [[menu.main]]
# name = "Archive"
# identifier = "archive"
# url = "/posts/"
# weight = 4

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/

[params.anubis2]
enableSummary = true

socialIcons = [
    { id = "github", url = "https://github.com/SalmaGhareeb" },
    { id = "linkedin", url = "https://www.linkedin.com/in/salmahabdelhady/" },
    { id = "email", url = "salmaghareeb@gmail.com" },
]

# Leave all parameters empty to use the default values.
